name: GitHub Actions
on:
  push:
    branches:
      - 'main'
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t iheb.jarrar/docker-react -f Dockerfile.dev -- --coverage
      - name: Run tests
        run: docker run iheb.jarrar/docker-react npm run test
